# grep -nr "85ea1a0d49ef26163ca64b1f4b65a805" ride-manager-release-*/*.unicorn

params = {
  pickup_location_hash:{
    postal_code:"60666",
    latitude:"41.977584",
    longitude:"-87.90296549999999",
    line1:"10000 W O'Hare Ave",
    city:"Rosemont",
    state:"IL"},
  dropoff_location_hash:{
    postal_code:"61008",
    latitude:"42.204735",
    longitude:"-88.84292499999999",
    line1:"3088 Flora Road",
    city:"Belvidere",
    state:"IL"},
  pickup_time:"2023-03-10 17:51:24",
  user_id:"129238",
  virtualize:"true",
  estimate_fares:"true",
  estimate_fees:"true",
  payments_service_payment_method_id:"89394",
  service_type_key:"taxi",
  booking_requirements:"",
  metadata:"",
  total_passengers:"1",
  booking_channel_key:"iphone_taxi_magic",
  version:"2",
  provider_ids:"",
  copay_program:""
}

pickup_location = LocationSearch.location_from_hash(params[:pickup_location_hash])
dropoff_location = LocationSearch.location_from_hash(params[:dropoff_location_hash])

search_context = SearchContext.new(
  :pickup_location => pickup_location,
  :dropoff_location => dropoff_location,
  :pickup_time => Time.parse(params[:pickup_time]),
  :pickup_time_local => Time.parse(params[:pickup_time]),
  :user => User.find_by_id(params[:user_id]),
  :mileage => SearchContext.straight_line_distance(pickup_location, dropoff_location),
  :booking_channel_bitmask => 8192,
  :wav_ride => Booking::ServiceTypeChecker.new(params).wav_requested?,
  :market_key_name => nil,
  :total_passengers => params[:total_passengers] || 1,
  :incentive_type => nil
)

search_hash = {"only_bookable"=>false, "non_integrated_with_integrated"=>false, "branded_with"=>false, "if_any_branded_with"=>false, "only_taxis"=>false, "only_provider"=>false, "only_taxis_and_ny_sedans"=>false, "non_verified_with_verified"=>false, "service_type_key"=>"taxi", "payment_method_type"=>"credit_card", "estimate_fares"=>true, "estimate_fees"=>true, "filter_out_non_favorites_if_any_favorites"=>false, "halo_protection"=>false, "auto_estimate"=>false, "ignore_company_discount"=>false, "down_providers_in_directory"=>true, "virtualize"=>true, "ridecharge_payment"=>true}

fleet_search_results = ProviderSearchResult.find(
  search_context,
  search_hash
).sort

fleet_search_results
# [
# #<ProviderSearchResult:0x000000000cf5a800 
# @provider=#<ProviderService id: 61,
# company_id: 21,
# name: "Chicago W2C Pairing",
# verified: true,
# customer_service_number: " ",
# billing_number: nil,
# dispatch_system_id: 35,
# dispatch_system_down: false,
# monitor_dispatch_system: false,
# service_type: "TAXI",
# service_type_bit_mask: 1,
# cancel_ride_cutoff_time: 0,
# api_key: "CHICAGO",
# max_lead_time: 1209600,
# accepts_rides: true,
# logo: nil,
# service_url: "https://way2i-taxi.stage.gocurb.com:6443/",
# rate_calculator_id: 44,
# low_tech_dispatch_enabled: false,
# use_serviced_counties: false,
# airport_pickup_messaging: false,
# billing_type: "realtime",
# pre_auth_cc: true,
# fleet_id: nil,
# dispatch_data_id: nil,
# dispatch_data_type: nil,
# restricted_search: 0,
# region_id: 19,
# search_algorithm: "pickup_must_be_in_service_area",
# custom_booking_rules_class: nil,
# custom_cancellation_rules_class: nil,
# vehicle_translation_class: nil,
# type: "ProviderService",
# provider_group_id: nil,
# priority_provider_id: nil,
# key_name: "chicago_w2c_pairing",
# rips_key: nil,
# real_time_system_active: false,
# vehicle_wizard: true,
# requires_rate: false,
# must_enter_confirmation_number: false,
# provider_client_tester_id: nil,
# report_recipients: nil,
# dispatch_send_postal_code: nil,
# tip_type: "estimated",
# tip_attribute: nil,
# book_without_async_rates: nil,
# in_car_cash_permitted: true,
# dispatch_phone_number: nil,
# rank: 100,
# vip_level: nil,
# referral_fee: nil,
# referral_rate: nil,
# cash_channel_bitmask: 17956864,
# driver_name_formatter_id: nil,
# dispatch_sms_enabled: false,
# dispatch_sms_default_area_code: nil,
# dispatch_sms_calltaker_option: false,
# total_vehicles: nil,
# dispatch_recording_enabled: true,
# send_ride_emails: true,
# sms_marketing_provider_id: nil,
# accounting_group_id: 22,
# average_ride_cost: 25,
# cash_only: false,
# debug_dispatch_system: true,
# time_zone_olson_id: 41,
# locale: "en_US",
# country_code: "US",
# show_address: true,
# show_time_to_dispatch: false,
# show_time_to_pick_up: false,
# wheel_chair_accessible: nil,
# computerized_dispatch: true,
# mission: nil,
# gps_tracking: 1,
# coming_soon: false,
# credit_card_swipe_style_id: nil,
# credit_card_swipe_style_key: nil,
# iphone_logo: nil,
# location_id: nil,
# phoned_count: 0,
# created_at: "2016-09-22 14:19:13",
# updated_at: "2022-05-19 10:57:24",
# tag_line: nil,
# booking_smsc_id: nil,
# send_voucher_pdf_to: nil,
# send_provider_report_to: nil,
# test_location_id: nil,
# reference_location_id: nil,
# gps_refresh_rate: 20,
# direct_message_drivers: true,
# ivr_dispatch_notifications: false,
# twilio_verified_phone_number: false,
# service_fee_type: "absolute",
# number_of_dispatch_offers: nil,
# seconds_for_dispatch_offer: nil,
# booking_fee: 0.195e1,
# charge_rc_payment_referral_fee: true,
# virtual: false,
# credit_card_channel_bitmask: 65535,
# merchant_card_processing_fee: 0.0,
# fixed_processing_fee: 0.0,
# variable_processing_rate: 0.0>,
# @provider_id=nil,
# @estimated_fare=146.3,
# @estimated_rider_fare=166.73,
# @estimated_base_fare=168.16,
# @estimated_fee=1.5,
# @estimated_fare_components={:improvement_surcharge=>1.0,
# :state_surcharge=>0.5,
# :driver_discounted_fare=>146.3,
# :rider_discounted_fare=>166.73,
# :base_fare=>168.16,
# :driver_surge=>nil,
# :minimum_fare_adjustment=>nil,
# :driver_visible_incentives_amount=>nil,
# :estimated_distance=>60.18166405877599,
# :estimated_time=>60.833333333333336,
# :driver_discount=>0.13,
# :marketplace_pricing=>true,
# :rider_discount=>0.01,
# :rider_upcharge=>0.25,
# :tip_amount=>33.65,
# :tip_percentage=>20},
# @estimate_id=1427056,
# @supported_fare_type="flat",
# @no_service_fee=true,
# @fares=[{:type=>:fare,
# :name=>"Fare",
# :amount=>146.3},
# {:type=>:rider_fare,
# :amount=>166.73},
# {:type=>:base_fare,
# :amount=>168.16},
# {:type=>:surge,
# :amount=>nil},
# {:type=>:minimum_fare_adjustment,
# :amount=>nil},
# {:type=>:driver_visible_incentives_amount,
# :amount=>nil},
# {:type=>:company_discount_amount,
# :amount=>nil},
# {:type=>:est_distance,
# :value=>60.18166405877599},
# {:type=>:est_time,
# :value=>60.833333333333336},
# {:type=>:market_service_detail_id,
# :value=>67},
# {:type=>:metered_if_possible,
# :value=>nil}],
# @service_area=#<ServiceAreaZone id: 547,
# type: "ServiceAreaZone",
# service_area_group_id: 52,
# postal_code: nil,
# county: nil,
# state: nil,
# location_id: nil,
# zone_id: 129,
# extras_direction_code: nil,
# extras_amount: nil,
# active: true,
# pickup_range: false,
# excluded: false,
# created_at: "2020-06-16 22:18:48",
# updated_at: "2022-04-08 11:10:11",
# channel_bitmask: 33439711,
# country_id: 1,
# fsa: nil,
# extended_dropoff_range: false,
# halo: false>,
# @service_area_id=nil,
# @service_area_group=#<ServiceAreaGroup id: 52,
# name: "Chicago W2C Pairing SAG",
# active: true,
# created_at: "2017-08-16 19:22:49",
# updated_at: "2017-08-16 19:22:49">,
# @service_area_group_id=nil,
# @modifiers=[],
# @messages=[],
# @popups=[],
# @viewable=true,
# @pickup_and_dropoff_match=true,
# @from_call_stand=false,
# @flat_discount=0.13,
# @flat_rider_discount=0.01,
# @flat_company_discount=nil,
# @driver_upcharge=nil,
# @rider_upcharge=0.25,
# @surge_multiplier=nil,
# @flat_minimum=nil,
# @fare_minimum=9.5,
# @minimum_distance_in_miles=nil,
# @minimum_time_in_seconds=nil,
# @meterless=true,
# @incentive=nil,
# @incentives={},
# @company_id=nil,
# @marketplace_pricing=true,
# @static_fare=nil,
# @ride_id=nil,
# @fare_estimate_type=nil,
# @from_zone="chicago_ohare_airport",
# @to_zone="chicago",
# @route_id=nil,
# @route_polyline="uue_GfrowOu@lAiAzCa@pBCx@Gx@K|@`AJP@NCVKNQhFcMH]?e@Ke@{AsDeE{JeAkCg@e@w@QwGIq@Ia@Gk@@a@G_@Oi@a@g@{@Kg@Es@PmF?WPaA`@s@~AuBHY`AoAtCoDtJgLh@{@n@wA`@oAj@cEDmACsBUkCs@yCaQmj@yFuQcEiN{@_Es@cF[kEM_HEcHRSJo@Pk@V_@h@Y^ERBVH\\ZT`@H`@BdAKl@MZUX]Ra@Fu@CaD_@mAWqCw@g@e@u@kAcAoCw@}Ae@e@_Aq@{@WSEMQg@GYE[Ag@AkBL{A^gM`EqBz@iA~@iA~A}@`CY`Aw@fC]x@]dA_@z@y@tA_ChC_@`@En@o@l@uDtDmAlAoApAoB~BiBpCyApCy@pBkDtJuPre@wRxi@}FjPeDxJ{@bDcAlEuEvWiQvcAw[|jB}B|NaApH_Fla@}Hjp@eBnNi@vDiA`F{ApEaBnDaAbB}BfD}BjD_K`OiO|TwY|b@{J|NaGpJiEdIiDhH{BnFgIxT}Pve@au@zsBeJdWiDbKoDhMaAzDyA~GcB`JmBjMeAxI{@rJyCre@mQ`uCoHplAuMxvBgHjjAm@hK[pHGfDAhG?hQ?r|A?zo@?lj@@rfCDzoHJ~dIDn~CMvIUzFm@~HqCfVoJlx@}Fxf@kDtY{@rGkAxGkAbFy@`DsJvYsIbWsXfy@mU`r@{d@duAob@poAkSdm@kB~FgCbJmBzH_g@xwBc@fBkAfEuBxGcB|EsCpHqCnHgNj^{g@nsAi_@vaAmDjJ{BzHcAdE{@rEmCtPsEpYsDlUwNh~@sVx}AwDrUgOl`A}L~v@aPhcAcDvQ}BpLkLzk@uV~nAqe@paCaPfx@yDhR}EzSwVdbAcj@lzB{]xvA}Pnr@{It]{DnOkKnb@mXpgA}FfVgKrb@cJd`@_Klb@wLvg@_FdVwGv\\wQl~@aLpk@mXruA{Qr~@yM|q@uKfj@wDvRqDdQuBxIaDjLyDlMoVhy@cPvi@yGpTuOnh@w@hDu@jEa@`Da@lEYjHCnJAhXC|UCxo@?nKA~BM\\AbACrAAlAK`D_@xBm@`BqBdEk@jAo@|AUjAC~@?zI@|QGpBG^K\\g@p@MNq@VsCrAkFbCWToBp@kBj@_Cr@{DjAP||@Lbl@BbO`C@hEAhO@`Q?fQBpr@ElzAFtD?jK??fBB`C",
# @route_path=nil,
# @estimated_surge=nil,
# @stepper=nil,
# @geocoder="google",
# @fare_estimate={"id"=>1427056,
# "ride_id"=>nil,
# "user_id"=>129238,
# "provider_id"=>61,
# "company_id"=>nil,
# "booking_channel_id"=>14,
# "service_type_id"=>2,
# "from_zone"=>"chicago_ohare_airport",
# "to_zone"=>"chicago",
# "from_latitude"=>41.977584,
# "from_longitude"=>-87.902966,
# "to_latitude"=>42.204735,
# "to_longitude"=>-88.842925,
# "estimated_distance"=>60.18,
# "estimated_time"=>60.83,
# "driver_discount"=>0.13,
# "rider_discount"=>0.01,
# "tip_percentage"=>20,
# "base_fare"=>16816,
# "driver_discounted_fare"=>14630,
# "rider_discounted_fare"=>16673,
# "rider_upcharge"=>25,
# "improvement_surcharge"=>100,
# "state_surcharge"=>50,
# "tip_amount"=>3365,
# "type"=>"Estimated",
# "no_service_fee"=>true,
# "marketplace_pricing"=>true,
# "total_fee"=>150,
# "total_fare"=>16823,
# "rider_fare"=>16823},
# @dropoff_required=false>
# ]




